name: Run Cypress API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # ✅ permite rodar manualmente

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.stats()'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Exibir variáveis de ambiente (debug)
        run: |
          echo "MONGO_URI=$MONGO_URI"
          echo "JWT_SECRET=$JWT_SECRET"

      - name: Subir aplicação em background
        run: |
          npm start & 
          sleep 15 # garante que a API está disponível antes do Cypress iniciar

      - name: Rodar testes Cypress
        run: npm run test
