name: Run Cypress API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Subir aplicação em background
        run: |
          npm start & 
          sleep 10

      - name: Rodar testes Cypress
        run: npm run test
